### ISSUE TITLE
breaking the observer dependent block nets you a block of one of the observed types

### ISSUE THREAD

**Issue by kotoroshinoto** [OpenMC/qCraft#9]
this is derped

**Comment by dariusc93** [comment]
Can you make it clear about your issue?

**Comment by kotoroshinoto** [comment]
i was trying to set up a portal, misplaced the observer dependant obsidian/gold block, when i went to pick it up, i got a regular gold block

**Comment by kotoroshinoto** [comment]
this is in server/client mode not single player btw

**Comment by dariusc93** [comment]
Could you provide me the version of qCraft you are using?

**Comment by kotoroshinoto** [comment]
it was the one linked from the minecraft forum post

https://dl.dropboxusercontent.com/u/75152928/[1.7.10] qCraft-1.2-OpenMCport-RobijnvogelTweak.jar

**Comment by dariusc93** [comment]
Try https://github.com/OpenMC/qCraft/releases/download/1.2/qCraft-1.2.jar . I do not know what changes was done to that jar itself, so I cannot verify nor debug anything. If it happens with this jar, let me know.

**Comment by kotoroshinoto** [comment]
same effect happens there when i break it it gives my the blocktype that it is rendering as, not the observation dependent block.

**Comment by kotoroshinoto** [comment]
Maybe its intended? it would seem it shouldn't be though.

**Comment by dariusc93** [comment]
I will review the code to see, but maybe it is.

**Comment by dariusc93** [comment]
Was it a normal gold block when you rejoin the server or restarted it? Any other mods on the server or client?

**Comment by kotoroshinoto** [comment]
there ARE other mods. I'm in the process of building a small nonpublic server for myself and my personal friends. (i host my pack on a password protected git server on my PC).

**Comment by kotoroshinoto** [comment]
i haven't tried unloading the chunk yet or restarting i can do that now.

**Comment by kotoroshinoto** [comment]
The ones that were part of the active gate are still showing up as ODB blocks after a logout.

Gonna place another one nearby and restart the server

**Comment by kotoroshinoto** [comment]
types were maintained from stop/start also. They only seem to lose their type when they break.

**Comment by kotoroshinoto** [comment]
its based on silk touch vs normal breaking. (looked at code).
